### ISSUE TITLE
32-bit versions of gstreamer packages

### ISSUE THREAD

**Issue by remyabel2** [negativo17/gstreamer1-plugin-libav#2]
If it's not too much hassle, can you provide 32-bit versions of the gstreamer packages? My primary use-case is winegstreamer. rpmfusion has them, but due to incompatibilities it would be a lot of effort to switch.

**Comment by scaronni** [comment]
Sorry for the delay, which packages?
```
gstreamer1-libav.x86_64
gstreamer1-plugins-bad.x86_64
gstreamer1-plugins-ugly.x86_64
gstreamer1-svt-av1.x86_64
gstreamer1-svt-vp9.x86_64
gstreamer1-vaapi.x86_64
```

**Comment by remyabel2** [comment]
I believe {libav, bad, ugly} would be the appropriate one. Thanks!

**Comment by scaronni** [comment]
Ugh... this means building every package for 32 bit, as libav depends on ffmpeg which depends on a gazillion libraries and bad has its lot of dependencies as well. What is the use case for the 32 bit gstreamer packages?

**Comment by scaronni** [comment]
I mean, what do you do with winegstreamer?

**Comment by remyabel2** [comment]
No need to sweat it then. I didn't think of the transitive dependencies.

32-bit winegstreamer is needed for wine (which relies on 32-bit libraries primarily for games) that play movies and if the 32-bit gstreamer libraries are not available, wine will not have access to those decoders.

**Comment by scaronni** [comment]
How is Steam sorting that out with Proton? I have plenty of games that run flawlessly (some require some small [adjusmtent](https://github.com/scaronni/steam-proton-mf-wmv)) and there is no builtin 32 bit Gstreamer libraries of any sort.

**Comment by remyabel2** [comment]
I'm pretty sure proton does it differently from vanilla wine. I don't know the exact details, but as I understand it Valve is trying to move away from proprietary codecs and internally they do some sort of translation for their decoder. Naturally they want compatibility for all of their games, so it makes sense that it works out of the box for 90% of games (except those that require the media foundation fix, which is included by default in proton-ge). There are some games that use ancient codecs or those that simply are not used by the majority of games and therefore are edge cases, one being the Inedo codec for SWAT 3. A mod re-encodes these in xvid (and more recently mpeg-4). After hours of troubleshooting I narrowed the issue down to a missing gstreamer library. 

Again, my use-case is very specific and since the work is disproportionate I won't ask you to package it. I'll just switch to rpmfusion for this situation.

**Comment by scaronni** [comment]
OK, thanks for the information. This is the first time I've received such a use case.
